### ISSUE TITLE
Sort lists alphabetically 

### ISSUE THREAD

**Issue by jrhbcn** [nanawel/our-shopping-list#13]
Hi,

Is it possible to sort items alphabetically in both check/uncheck views?

Thanks.

**Comment by nanawel** [comment]
Hi,

It was the initial sort order until recently, but it turned out to be not really handy when checking an item by mistake, so I replaced it with a "sort by recently checked date" instead.

I'm trying to keep the UI with the minimum necessary elements, so I might add this feature togglable with a server-wide flag.
Would it help in your use case?

**Comment by nanawel** [comment]
See also #8 btw.

**Comment by jrhbcn** [comment]
Hi @nanawel,

Yes, a server wide flag should be enough. Like a environmental variable for instance (I use docker compose).

Many thanks for taking this option into consideration.

**Comment by nanawel** [comment]
Feature released in 2.6.0 via 7d99271c2c15b1c407bcb8a268531428eaaca89d
