### ISSUE TITLE
feat: quantity input detection

### ISSUE THREAD

**Issue by taku-nm** [nanawel/our-shopping-list#20]
It would be sensible to allow for a sort of rich input detection using a specific syntax to detect quantity, avoiding the extra step of creating an entry only to then edit it.
I'd suggest something like
`2x Toast`
in order to create an entry called Toast with the quantity set to 2.

Ideally this would be a settings that one can enable on a per list or maybe per board basis.

**Comment by nanawel** [comment]
That could be handy indeed.
On the same topic, a user recently suggested that adding a new item could automatically open the "details" popin in order to set additional info without having to search and reopen the item that's just been created.

I guess both ideas are good but should be toggleable using configuration on a per instance level.

**Comment by nanawel** [comment]
Merry Xmas :santa: You should be able to test this feature on https://dev.osl.lanterne-rouge.info/

If it's okay for you, I'll soon publish a 2.9.0 with it.

**Comment by taku-nm** [comment]
Merry Christmas! This looks very good but it would need an option to disable the automatic details pop-up. After all it's just adding another click which I certainly don't need given that it already detects the 2x format for quantity and I never use the details panel.

**Comment by nanawel** [comment]
Of course, each feature will be toggleable with the following variables:

- `VUE_APP_USE_ITEM_QUICK_SYNTAX` (default: `false`)
- `VUE_APP_EDIT_ITEM_ON_CREATE` (default: `false`)

**Comment by nanawel** [comment]
Released in [2.9.0](https://github.com/nanawel/our-shopping-list/releases/tag/2.9.0).
