### ISSUE TITLE
mongodb issue 

### ISSUE THREAD

**Issue by houdini69** [nanawel/our-shopping-list#26]
I have an issue with mongodb appearing randomly and causing Our Shopping List to malfunction. See the screenshot. I'm using the Docker version. I can note many requests in my pihole which do not appear normally.
![osl_mongodb](https://github.com/nanawel/our-shopping-list/assets/24533104/f00df10d-9a27-4088-82d8-66ef5b1b3ac4)

**Comment by nanawel** [comment]
Hi @houdini69 
It might be because your mongodb container is crashing and restarting regularly. Of course it should not, but you should be able to learn more using

```shell
docker-compose logs -f --tail=50 mongodb
```

It will display the logs from the container and start following them. Try to find the traces of the error from there.

Possible causes can be :
- insufficient disk space
- insufficient memory (leading to OOM-kill)
- corrupted database files (in this case, it might be better to start from scratch again)

**Comment by houdini69** [comment]
I noticed that I had the same problem with mongodb when I restart my server even after updating my docker-compose file

**Comment by Vultilion** [comment]
Still got this issue once a day after reboot.
MDB receives Signal 15 (SIGTERM). Is can be only from our-shopping-list.

**Comment by nanawel** [comment]
That sounds a lot like https://stackoverflow.com/questions/77298407/irregular-docker-restarts-receiving-signal-15-with-unknown-origin

BTW if you're not already using the **version 7 of MongoDB**, I can strongly advise you to upgrade and see if it still occurs. I forgot to follow Mongo's versions so I left OSL stuck to v4 a bit too long (until june 2024).

See instructions here to keep your data intact: https://github.com/nanawel/our-shopping-list?tab=readme-ov-file#upgrade-mongodb-to-7x

**Comment by houdini69** [comment]
Thanks. I applied the script to update MongoDB and after restart no more issue.

**Comment by nanawel** [comment]
Glad it worked!
Though I never got this erratic behiavour you were describing, even when using Mongo v4 for several years.
